[dependencies]
  matrix4cj = {git = "https://gitcode.com/Cangjie-TPC/matrix4cj.git", branch = "cjc_0.53.13", version = "1.0.0"}

[package]
  cjc-version = "0.53.13"
  compile-option = ""
  description = "Numpy alternative for Cangjie"
  link-option = ""
  name = "numcj"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
